angular.module('app', ['pascalprecht.translate','ngSanitize'], function ($translateProvider) {
    $translateProvider.useSanitizeValueStrategy('sanitize');

    // Adding a translation table for the English language
    $translateProvider.translations('en_US', {
        "today"     : "today",
        "about"     : "About",
        "contacts"     : "Contacts",
        "interests"     : "Interests",
        "expirience"     : "Work Expirience",
        "education"     : "Education",
        "strong"     : "Core Skills",
        "weak"     : "Other Skills",
        "portfolio"     : "Portfolio",
        "more"     :        "There is more information and examples on my github and linkedIn accounts."
    });

    // Adding a translation table for the Russian language
    $translateProvider.translations('ru_RU', {
        "today"     : "сейчас",
        "about"     : "Обо мне",
        "contacts"     : "Контакты",
        "interests"     : "Интересы",
        "expirience"     : "Опыт работы",
        "education"     : "Образование.",
        "strong"     : "Основные навыки",
        "weak"     :    "Другие навыки",
        "portfolio"     : "Портфолио",
        "more"     :        "Больше работ и информации о проектах на аккаунтах в github и linkedIn."
    });

})
.controller("ctrl",function($scope,$translate,$http){



        $scope.lang = "";
        $scope.view = "document";
        $scope.changeView = function() {
            $scope.view = ($scope.view == "document" )? "web" : "document";
            $scope.web = $scope.view == "web";
        };
        $scope.setLang = function(langKey) {

            $http.get("data/" + langKey + ".json").then(function(data){

                var _b = ["jobs", "edus", "works"];
                for (var b in _b){
                    var _arr = data.data[_b[b]];
                    for (var i in _arr) {
                        _arr[i].begin = _arr[i].begin && new Date(_arr[i].begin);
                        _arr[i].end = _arr[i].end && new Date(_arr[i].end);
                    }
                }

                $scope.data = $.extend(true,$scope.data,data.data);

                // You can change the language during runtime
                $translate.use(langKey);
                // A data generated by the script have to be regenerated
                //$scope.jsTrSimple = $translate.instant('SERVICE');
                //$scope.jsTrParams = $translate.instant('SERVICE_PARAMS', $scope.tlData);
                $scope.lang = langKey;
            })

        };

        $scope.data = {};

        function resize(){
            var art = $("article");
            var a = ($(window).height() - 20) / art.height() ;
            art.css("transform","scale(" + a +")");
            var _w =  art.width() * a;
            var _h =  art.height() * a;
            $(".container").width(_w).height(_h);
        }

        //$(window).resize(resize);
        setTimeout(resize);

        $scope.setLang("en_US");

})