angular.module('app', ['pascalprecht.translate','ngSanitize'], function ($translateProvider) {

    // Adding a translation table for the English language
    $translateProvider.translations('en_US', {
        "about"     : "About",
        "contacts"     : "contacts",
        "interests"     : "interests",
        "expirience"     : "Work Expirience",
        "education"     : "education",
        "strong"     : "Core Skills",
        "weak"     : "Core Skills",
        "portfolio"     : "portfolio",
        "more"     :        "There is more information and examples on my github and linkedIn accounts.",
    });

    // Adding a translation table for the Russian language
    $translateProvider.translations('ru_RU', {
        "about"     : "Обо мне",
        "contacts"     : "Контакты",
        "interests"     : "Интересы",
        "expirience"     : "Опыт работы",
        "education"     : "Образование.",
        "strong"     : "Основные навыки",
        "weak"     :    "Другие навыки",
        "portfolio"     : "Портфолио",
        "more"     :        "Больше работ и информации о проектах на аккаунтах в github и linkedIn.",
    });

})
.controller("ctrl",function($scope,$translate){



        $scope.setLang = function(langKey) {
            // You can change the language during runtime
            $translate.use(langKey);
            // A data generated by the script have to be regenerated
            //$scope.jsTrSimple = $translate.instant('SERVICE');
            //$scope.jsTrParams = $translate.instant('SERVICE_PARAMS', $scope.tlData);
            $scope.data = $.extend(true,$scope.data,$scope.data[langKey]);
        };


        var ru =



        $scope.data = {

            ru_RU: {
                name: "Пономарев Денис",
                title: "Фронтенд ВЕБ Программист",
                avatar: "rus.jpg",
                prompt: "Фронтенд разработчик и программист с 4-хлетним опытом работы.  Имею опыт разработки вебсайтов и html5 приложений, десктопных и мобильных приложений с использованием C++/Qt, Java/swing  и Android development Kit",

                strong_description: "<p>2 года разработки с использованием HTML5 технологий, таких как SVG, Canvas, web workers. JavaScript, JQuery, ajax. </p><p>Опыт работы с фреймворками: RaphaelJS, KineticJS, BackBoneJS. </p><p>Участие в разработке модулей для крупных систем на  PHP  и Java. Имею опыт работы с JSP, Smarty, MySQL.</p><p>Имею основные навыки работы с Python и Django.</p>",
                weak_description: "<p>Разработка приложений на C++ (Qt/ Visual C++), Java, OpenGL, mySQL, SQLite</p><p>Имею опыт портирования приложений на мобильные платформы с использованием Android SDK, C++ / Android NDK</p>",
                info: {
                    adress: {"dt": "Адрес", value: "Тольятти, Россия, 445027"},
                    birth: {"dt": "Дата рождения", value: "9 Янв 1991 (24 года)"},
                    marital: {"dt": "Семейное положение", value: "Не женат"}
                },
                interests: {
                    travel: {
                        value: "Люблю путешествовать"
                    },
                    volunteer: {
                        value: "Учавствовал в волонтерских программах и организации мероприятий с иностранными волонтерами."
                    },
                    fire: {
                        value: "Люблю велосипед и скалолазание. Выступаю с группой огненного шоу."
                    }
                },
                jobs: {
                    upwork: {
                        company: "Фриланс",
                        title: "Фронтенд программист",
                        job_description: "Разработка веб приложений на AngularJS/ NodeJS.",
                    },
                    inteduca: {
                        city: "Москва",
                        title: "Фронтенд программист",
                        company_description: "Интедука разработывает образовательные игры для обучения персонала таких компаний, как Megafon, Canon , Pepsico и другие",
                        job_description: "Работал с AngularJS над приложениями для Megafon, Canon, Pepsico и других",
                    },
                    gamesinedu: {
                        city: "Москва",
                        title: "Фронтенд программист",
                        company_description: "Clients include:  Skolkovo Moscow School of Management,  Rosatom Nuclear Energy State Corporation,  Russian Presidential Academy of National Economy and Public Administration",
                        job_description: "В мои обязанности входила, доработка игровых моделей бизнес-игр,  верстка и разработка интерактивных карт и элементов дизайна, разработка web-приложений",
                    },
                    brightstudio: {
                        city: "Тольятти",
                        title: "ВЕБ программист",
                        job_description: "Разработка  веб-сайтов на системе UMI-CMS."
                    },
                    dkc: {
                        company: "DKC Russia",
                        city: "Тольятти",
                        title: "Qt/C++ Программист",
                        company_description: "KC works under its mission – to provide international customers by hi-tech products for electrical installations.",
                        job_description: "Разработка  Fix Combitech 2."
                    },
                    polad: {
                        company: "ЗАО «ПОЛАД»",
                        city: "Тольятти",
                        title: "Системный администратор",
                        job_description: " Первая официальная работа в сфере IT. В мои обязанности входила поддержка пользователей, настройка локальной сети ПОЛАД и доработка корпоративного сайта компании.",
                    }
                },

                edus: {
                    tltsu: {
                        company: "ТГУ",
                        city: "Тольятти",
                        title: "Специалист,  математик - программист",
                        company_description: "Прикладная математика и информатика",
                        job_description: "Тольяттинский Государственный Университет, 5 лет. Диплом"
                    },
                    ncedu: {
                        company: "NetCracker",
                        city: "Тольятти",
                        title: "Java programmer",
                        company_description: "УНЦ «инфоком» NetCracker",
                        job_description: "Курсы: Программирование на Ja SE/EE, 130 часов, БД Oracle 96 часов"
                    },
                    itschool: {
                        company: "Школа ИТ",
                        city: "Тольятти",
                        title: "Инженер- программист",
                        company_description: "НОУ 'Школа Информационных технологий'",
                        job_description: "Инженерная информатика, 976 часов . ECDL Сертификат"
                    }
                },

                works: {
                    rosatom: {
                        title: "Управление в ядерной энергетике",
                        company: "ГК РосАтом",
                        description: "обязанности: верстка, разработка всех интерактивных карт и элементов. Программирование игровой модели",
                    },
                    sokrat: {
                        title: "HTML5 Тренажер по сзематизации.",
                        description: "Разработка веб-тренажера по схематизации. Приложение используется как образовательный инструмент в школах менеджмента.",
                    },
                    teacher: {
                        title: "Симулятор учителя",
                        description: "Симулятор учителя."
                    },
                    photofieria: {
                        title: "Редактор Альбомов",
                        description: "Редактор альбомов с поддержкой фильтров, обрезки изображений, рамок , форматировани текста и т.д. Оптимизирован для работы на планшетах и телефонах"
                    },
                    planogram: {
                        title: "Редактор полки",
                        description: "Симулятор мерчандайзига.  Выложи свою полки."
                    },
                    dialogs: {
                        title: "Интерактивные туры, тесты, диалоги",
                        clients: ["Pepsico", "Megafon", "Canon", "Sberbank"],
                        description: "Интерактивные туры, тесты, диалоги ."
                    },
                    atom3: {
                        title: "Atom3 simulator: Interactive Charts",
                        description: "Программирование элементов интерфейса"
                    },
                    smb: {
                        title: "симулятор \"Малый и средний бизнесс\"",
                        description: "разработка интерактивных карт и элементов"
                    },
                    fc2: {
                        href: "http://www.dkc.ru/en/support/software/",
                        description: "Версия программы «FIX Combitech 2.0» предназначена для расчета аксессуаров и крепежа металлических лотков.",
                        details: "Features:<ul><li>Save and load projects, Export to Excel, Word and XML</li><li>local and network databases.</li><li>Self- update system</li></ul>",
                    },
                    mwx: {
                        title: "MinesWeeper Extended",
                        description: "Создание расширенной версии игры сапер. Поддержка различных типов игрового поля, поддержки модификаций на JavaScript, Портирована на Android.",
                        skills: ["cpp", "Qt", "OpenGL"],
                    }
                }
            },
            en_US: {
                name: "Ponomarev Denis",
                avatar: "avatar.jpg",
                title: "Front-End Web Developer",
                prompt: " I am a front-end developer with about 4 years of experience in web development. During last years I developed a number of web sites and applications using latest web standarts. This is what I do and what am I like to do.",


                strong_description: "<p>My strongest skills are <b>HTML5</b>, <b>CSS3</b> and <b>javascript</b>. I prefer to use <b>AngularJS</b>, <b>LESS</b> and <b>MongoDB</b>/<b>NodeJS</b> or frameworks like <b>Angular-Meteor</b> in my applications.</p> <p>I worked a lot with enchanced HTML5 graphics (presentations, schemes, charts etc). I used <b>RaphaelJS</b> for SVG; <b>EaselJS</b>, <b>KineticJS</b>, <b>FabricJS</b> for CANVAS; <b>ThreeJS</b> for WebGL.</p><p>I developed cross-browser and cross-platform web applications, with modern features and and polyfills for old and mobile browsers (Android, iOS, IE8). Expirienced with creating mobile apps packaged through <b>PhoneGap</b>.</p>",
                weak_description: " <p>Before i set priority on Web FrontEnd i mostly worked on <b>Qt</b>. Created Linux/Windows/Android applications. Finished different programming courses.</p>",
                info: {
                    adress: {
                        //icon: "fa-map-pin",
                        title: "adress",
                        value: "Togliatty, Russia, 445027",
                        href: "https://www.google.ru/maps/place/prospekt+Stepana+Razina,+42,+Tolyatti,+Samarskaya+oblast'/data=!4m2!3m1!1s0x41687981e2c58a55:0xb5d3b60bdbfe49c4?sa=X&ved=0CBsQ8gEwAGoVChMI_9Lp3b39xwIVwqpyCh1VOQ8J",
                        "dt": "Adress"
                    },
                    birth: {"dt": "Birth Date", value: "9 Jan 1991 (24 years)"},
                    marital: {"dt": "Marital Status", value: "single"}
                },
                interests: {
                    travel: {
                        icon: "fa-plane",
                        value: "Travelling is my passion, opporunity to travel is always a good point for me"
                    },
                    volunteer: {
                        icon: "volunteer",
                        value: "I`ve been a participant in different youth exchange programs, organized events with foreign volunteers."
                    },
                    fire: {
                        icon: "fire",
                        value: "I like Cycling and climbing. As a member of trickers group I perform with fire-show."
                    }
                },
                strong: {
                    "angular": {icon: "angular", title: "AngularJS"},
                    "html5": {icon: "html5", title: "HTML5"},
                    "css3": {icon: "css3", title: "CSS3"},
                    "svg": {icon: "svg", title: "SVG"},
                    "canvas": {icon: "canvas", title: "Canvas"},
                    "nodejs": {icon: "nodejs", title: "NodeJS"},
                    "phonegap": {icon: "phonegap", title: "PhoneGap"}
                },
                weak: {
                    "qt": {icon: "qt", title: "Qt"},
                    "mysql": {icon: "mysql", title: "MySQL"},
                    "cpp": {icon: "cpp", title: "C++"},
                    "java": {icon: "java", title: "Java"},
                    "php": {icon: "php", title: "PHP"},
                    "opengl": {icon: "opengl", title: "OpenGL"},
                    "photoshop": {icon: "photoshop", title: "PhotoShop"}
                },
                contacts: {
                    email: {
                        icon: "fa-envelope",
                        title: "email",
                        value: "ponomarevtlt@gmail.com",
                        href: "mailto:ponomarevtlt@gmail.com"
                    },
                    skype: {
                        icon: "fa-skype",
                        title: "skype",
                        value: "den.ponomarev",
                        href: "skype:den.ponomarev?call"
                    },
                    whatsapp: {
                        icon: "fa-whatsapp",
                        title: "whatsapp",
                        value: "+7-927-020-3657",
                        href: "tel:+79270203657"
                    },
                    facebook: {
                        icon: "fa-facebook-square",
                        title: "facebook",
                        value: "fb.com/hometlt",
                        href: "fb.com/hometlt"
                    },
                    github: {
                        icon: "fa-github-square",
                        title: "github",
                        value: "github.com/hometlt",
                        href: "github.com/hometlt"
                    },
                    linkedin: {
                        icon: "fa-linkedin-square",
                        title: "linkedin",
                        value: "linkedin.com/in/ponomarevtlt",
                        href: "linkedin.com/in/ponomarevtlt"
                    }
                },
                jobs: {
                    upwork: {
                        begin: new Date("May 2015"),
                        company: "Free-lance",
                        title: "Web Frontend Programmer",
                        job_description: "HTML5 applications based on AngularJS/ NodeJS stack.",
                        skills: ["angular", "html5", "css3", "canvas", "nodejs"]
                    },
                    inteduca: {
                        begin: new Date("Jan 2014"),
                        end: new Date("May 2015"),
                        company: "Inteduca",
                        city: "Moscow",
                        href: "http://www.levellab.ru",
                        href_title: "www.levellab.ru",
                        title: "Web Frontend Programmer",
                        company_description: "'Inteduca' creates tools and educational games. Clients includes: F  Russia,  Megafon, Canon Russia,  e t.c.",
                        job_description: "Worked with AngularJS applications for Pepsico, Canon, Palmolive etc.",
                        skills: ["html5", "angular", "canvas"]
                    },
                    gamesinedu: {
                        begin: new Date("Feb 2012"),
                        end: new Date("Aug 2013"),
                        company: "GamesInEdu",
                        city: "Moscow",
                        href: "http://gamesinedu.rane.ru",
                        href_title: "gamesinedu.rane.ru",
                        title: "Web Frontend Programmer",
                        company_description: "Clients include:  Skolkovo Moscow School of Management,  Rosatom Nuclear Energy State Corporation,  Russian Presidential Academy of National Economy and Public Administration",
                        job_description: "Created larger part of UI of web based educational simulators for Russian government structures and universities",
                        skills: ["svg", "canvas", "php"]
                    },
                    brightstudio: {
                        begin: new Date("Sep 2011"),
                        end: new Date("Dec 2011"),
                        company: "Bright Studio",
                        city: "Togliatty",
                        href_title: "www.brightstudio.ru",
                        href: "http://www.brightstudio.ru",
                        title: "Web Programmer",
                        company_description: "",
                        job_description: "I tried myself in web design and development creating websites running on PHP and UMI-CMS.",
                        skills: ["php"/*,"umi"*/]
                    },
                    dkc: {
                        begin: new Date("Sep 2011"),
                        end: new Date("Dec 2011"),
                        company: "DKC Russia",
                        city: "Togliatty",
                        href_title: "www.dkc.ru",
                        href: "http://www.dkc.ru",
                        title: "Qt/C++ Software Developer",
                        company_description: "KC works under its mission – to provide international customers by hi-tech products for electrical installations.",
                        job_description: "I Developed Fix Combitech 2 software using Qt/C++ and MySQL/SQLite.",
                        skills: ["qt", "mysql"]
                    },
                    polad: {
                        begin: new Date("Jun 2009"),
                        end: new Date("Aug 2009"),
                        company: "Polad",
                        hide: true,
                        city: "Togliatty",
                        href_title: "www.polad.ru",
                        href: "http://www.polad.ru",
                        title: "System Administrator",
                        company_description: "KC works under its mission – to provide international customers by hi-tech products for electrical installations.",
                        job_description: "I Developed Fix Combitech 2 software using Qt/C++ and MySQL/SQLite."
                    }
                },
                edus: {
                    tltsu: {
                        begin: new Date("Jan 2008"),
                        end: new Date("May 2013"),
                        company: "TLTSU",
                        city: "Togliatty",
                        href: "http://tltsu.ru",
                        href_title: "tltsu.ru",
                        title: "Specialist of Mathematics and Information Technology",
                        company_description: "Faculty of Mathematics, physics and IT",
                        job_description: "Togliatty State University, 5 years. Diploma Supplement",
                        skills: ["cpp", "mysql", "opengl"]
                    },
                    ncedu: {
                        begin: new Date("2010"),
                        end: new Date("2011"),
                        company: "NetCracker",
                        city: "Togliatty",
                        href: "http://tlt.ncedu.ru",
                        href_title: "tlt.ncedu.ru",
                        title: "Java programmer",
                        company_description: "",
                        job_description: "Courses: Java SE/EE, 130 hours, Oracle DB 96 hours",
                        skills: ["java"]
                    },
                    itschool: {
                        begin: new Date("2006"),
                        end: new Date("2007"),
                        company: "IT School: ",
                        city: "Togliatty",
                        title: "Software Engineering Specialist",
                        company_description: "",
                        job_description: "Course: Engineering and Programmings, 976 hours. ECDL Certificate",
                        skills: ["cpp"]
                    }
                },

                works: {
                    rosatom: {
                        title: "Nuclear plant management simulator",
                        company: "GamesInEdu",
                        client: "RosAtom",
                        description: "Simulator for Nuclear Energy State Corporation. Creating game models and UI (optimized for IE8 and iPad).",
                        href: "http://atom2.modeus.info",
                        begin: new Date("Jan 2013"),
                        end: new Date("Jul 2013"),
                        //images: ["image019.png","image021.png","image023.png","image025.png","image027.png","image029.png"]
                        images: ["image021.png", "image029.png"]
                    },
                    sokrat: {
                        title: "HTML5 Scheme editor.",
                        company: "GamesInEdu",
                        description: "Development of scheme render and analyzer. Application used as educational tool in management Schools. It gives task to student and ask to draw the correct scheme.",
                        skills: ["HTML5", "canvas", "KineticJS"],
                        href: "http://sokrat.hometlt.ru",
                        begin: new Date("Sep 2012"),
                        end: new Date("Mar 2013"),
                        images: ["image031.png", "image033.png"]
                        //images: ["image031.png","image033.png","image035.png","image037.png","image039.png","image041.png"]
                    },
                    teacher: {
                        title: "Simulator of Teacher",
                        company: "GamesInEdu",
                        begin: new Date("2014"),
                        end: new Date("2014"),
                        description: "you are placed in a situation common to teachers - instruction, reviewing, planning, tutoring. FrontEnd Part visualize classroom, students and teachers, their actions during teaching process.",
                        images: ["image010.png"]
                    },
                    photofieria: {
                        title: "HTML5 Album editor.",
                        description: "Album editor is a tool to create presentations or photo albums with text and photos. It has editing tools like image filters/cropping/resizing, different borders/shapes/frames, text styling. It works also on phones and tablets.",
                        skills: ["HTML5", "canvas", "FabricJS"],
                        begin: new Date("May 2015"),
                        images: ["image043.png", "image045.png", "image047.png"]
                    },
                    planogram: {
                        title: "Planogram editor",
                        company: "Inteduca",
                        clients: ["Palmolive", "Colgate", "Baltimore"],
                        begin: new Date("2014"),
                        end: new Date("2014"),
                        description: "tool for merchandising simulator.  Interactive visual representations of a store's products.",
                        images: ["image003.png"]
                    },
                    dialogs: {
                        title: "Interactive Tours, Tests and dialogs",
                        company: "Inteduca",
                        href: "http://sb.hometlt.ru/",
                        clients: ["Pepsico", "Megafon", "Canon", "Sberbank"],
                        begin: new Date("2014"),
                        end: new Date("2014"),
                        description: "Educational tool for Pepsico employees. Interactive panoramas (virtual tours) with video elements,tests, photo and video dialogs. ",
                        images: ["image005.png", "image007.png"]
                    },
                    atom3: {
                        title: "Atom3 simulator: Interactive Charts",
                        company: "GamesInEdu",
                        begin: new Date("Jan 2014"),
                        end: new Date("Mar 2014"),
                        description: "Creating user interface elements",
                        images: ["image011.png", "image013.png"]
                    },
                    smb: {
                        title: "Simulator \"Small and medium business\"",
                        company: "GamesInEdu",
                        begin: new Date("Aug 2012"),
                        end: new Date("Apr 2013"),
                        href: "http://smb.modeus.info",
                        description: "crating game models and user interface",
                        images: ["image015.png", "image017.png"]
                    },
                    fc2: {
                        title: "Fix Combitech 2",
                        company: "DKC",
                        href: "http://www.dkc.ru/en/support/software/",
                        description: "FIX Combitech 2 is used by engineers in Russia and Ukraine to calculate accessories and fasteners metal trays.",
                        details: "Features:<ul><li>Save and load projects, Export to Excel, Word and XML</li><li>local and network databases.</li><li>Self- update system</li></ul>",
                        skills: ["cpp", "Qt", "MySQL", "SQLite"],
                        begin: new Date("Sep 2012"),
                        end: new Date("Mar 2013"),
                        images: ["image049.jpg", "image050.jpg"]
                    },
                    mwx: {
                        title: "MinesWeeper Extended",
                        href: "mwx.hometlt.ru",
                        description: "Extended version of the popular video-game \"Minesweeper\". Ported to Android, support external modifications, 3d scenes.",
                        details: "",
                        skills: ["cpp", "Qt", "OpenGL"],
                        begin: new Date("Jan 2011"),
                        end: new Date("May 2011"),
                        images: ["image055.jpg", "image061.jpg"]
                        //images: ["image053.jpg","image055.jpg","image057.jpg","image059.jpg","image061.jpg"]
                    }/*, {
                     title: "Mhpi.edu.ru, Mhpi.pw, Юнкера-мхпи.рф",
                     href:   "Mhpi.edu.ru",
                     description: "Creating a couple of websites for Moscow Institute of Arts and Industry",
                     details:    "",
                     skills: ["HTML","CSS","UMI-CMS","PHP"],
                     begin:  new Date("2012"),
                     end:    new Date("2013"),
                     images: []
                     //images: ["image053.jpg","image055.jpg","image057.jpg","image059.jpg","image061.jpg"]
                     },{
                     title: "AutoRodeo and Fire show",
                     href:   "http://new.kaskadery63.ru/",
                     description: "Trickers «Togliatty AutoRodeo» and Fire show group «Amon-Ra».auto moto show from my city and our local fire show group. Also, my hobbies. http://fire.hometlt.ru",
                     details:    "",
                     skills: ["HTML","CSS","UMI-CMS","PHP"],
                     begin:  new Date("2012"),
                     end:    new Date("2013"),
                     images: []
                     //images: ["image053.jpg","image055.jpg","image057.jpg","image059.jpg","image061.jpg"]
                     }*/
                }
            }
        };




        $scope.setLang("en_US");
            /*


        <p>Skills</p>
        <p>English:	advanced (participated in youth exchange programs, AIESEC, EVS, Work and Travel USA)</p>
        <p>Russian	native</p>
        <p>Front-end Development	Experienced in HTML5, cross-browser compatible CSS , LESS , Javascript.</p>
        <p>jQuery and AngularJS.</p>
        <p>frameworks:  SVG (RaphaelJS), Canvas (EaselJS, KineticJS, FabricJS), WebGL (ThreeJS).</p>
        <p>Back-End Development	PHP, NodeJS.</p>
        <p>Some experience with MEAN stack, SailsJS , Angular-Meteor.</p>
        <p>Software Development	Qt (Cross platform development for PC, Android and iOS)</p>
        <p>С++, Java, OpenGL </p>
        <p>related skills	Photoshop, Corel Draw</p>*/
})